<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8237" started-at="2017-07-13T10:37:36Z" finished-at="2017-07-13T10:37:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8237" started-at="2017-07-13T10:37:36Z" finished-at="2017-07-13T10:37:44Z">
      <class name="com.org.Functional.Tests.AppLandingTests">
        <test-method status="PASS" signature="LaunchApplication()[pri:0, instance:com.org.Functional.Tests.AppLandingTests@617faa95]" name="LaunchApplication" is-config="true" duration-ms="3575" started-at="2017-07-13T16:07:36Z" finished-at="2017-07-13T16:07:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method status="FAIL" signature="CheckAppLandingPage()[pri:0, instance:com.org.Functional.Tests.AppLandingTests@617faa95]" name="CheckAppLandingPage" duration-ms="44" started-at="2017-07-13T16:07:39Z" finished-at="2017-07-13T16:07:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Agile Cockpit Identity Server] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Agile Cockpit Identity Server] but found []
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.org.Functional.Tests.AppLandingTests.CheckAppLandingPage(AppLandingTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckAppLandingPage -->
        <test-method status="PASS" signature="disposeDriver()[pri:0, instance:com.org.Functional.Tests.AppLandingTests@617faa95]" name="disposeDriver" is-config="true" duration-ms="805" started-at="2017-07-13T16:07:40Z" finished-at="2017-07-13T16:07:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- disposeDriver -->
        <test-method status="PASS" signature="LaunchApplication()[pri:0, instance:com.org.Functional.Tests.AppLandingTests@617faa95]" name="LaunchApplication" is-config="true" duration-ms="3056" started-at="2017-07-13T16:07:40Z" finished-at="2017-07-13T16:07:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method status="FAIL" signature="CheckSuccessfulLogin()[pri:0, instance:com.org.Functional.Tests.AppLandingTests@617faa95]" name="CheckSuccessfulLogin" duration-ms="6" started-at="2017-07-13T16:07:43Z" finished-at="2017-07-13T16:07:43Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.org.pageControlsLibrary.AppLandingPageControls.txt_userName(AppLandingPageControls.java:16)
	at com.org.pageFunctionLibrary.AppLandingPageMethods.loginToApplication(AppLandingPageMethods.java:42)
	at com.org.Functional.Tests.AppLandingTests.CheckSuccessfulLogin(AppLandingTests.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckSuccessfulLogin -->
        <test-method status="PASS" signature="disposeDriver()[pri:0, instance:com.org.Functional.Tests.AppLandingTests@617faa95]" name="disposeDriver" is-config="true" duration-ms="733" started-at="2017-07-13T16:07:43Z" finished-at="2017-07-13T16:07:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- disposeDriver -->
      </class> <!-- com.org.Functional.Tests.AppLandingTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
